name: Initialize

on:
  create:
  
jobs:
  initialize:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
  
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - uses: octokit/request-action@v2.x
        id: repo-info
        with:
          route: GET /repos/${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Initialize
        run: | 
          echo "# ${{ github.event.repository.name }}" > README.md
          rm -f LICENSE
          
          TEMPLATE_OWNER=${{ fromJson(steps.repo-info.outputs.data).template_repository.owner.login }}
          if [[ "$TEMPLATE_OWNER" != "${{ github.repository_owner }}" && "$TEMPLATE_OWNER" != "${{ github.triggering_actor }}" ]]; then
            rm -f .github/FUNDING.yml
          fi
          
          rm -f .github/workflows/initialize.yml
          
      - name: Commit Initialization
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Initialized
